spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      host: localhost
      port: 27017
      database: helpdeskdb

springdoc:
  openapi:
    title: "User Service API"
    description: "Component responsible for user management created on Formação BackEnd Expert with Valdir Cezar"
    version: "1.0.0"



